// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DataRoot():Promise<string>;

export function ExportSession(arg1:string):Promise<string>;

export function GetEvents(arg1:string):Promise<Array<main.EventInfo>>;

export function GetReport(arg1:string):Promise<main.ReportInfo>;

export function GetSession(arg1:string):Promise<main.SessionInfo>;

export function Health():Promise<string>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function PickExecutable():Promise<string>;

export function PickFolder():Promise<string>;

export function RevealPath(arg1:string):Promise<void>;

export function RunAgent(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<main.SessionInfo>;
