// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DataRoot() {
  return window['go']['main']['App']['DataRoot']();
}

export function ExportSession(arg1) {
  return window['go']['main']['App']['ExportSession'](arg1);
}

export function GetEvents(arg1) {
  return window['go']['main']['App']['GetEvents'](arg1);
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function PickExecutable() {
  return window['go']['main']['App']['PickExecutable']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function RunAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunAgent'](arg1, arg2, arg3, arg4);
}
